### ISSUE TITLE
Unable to Configure "set add-route disable" in Phase1-Interface with Static Type

### ISSUE THREAD

**Issue by dimk21** [fortinet-solutions-cse/sdwan-advpn-reference#31]
Hey team!

I’m setting up a hub-and-spoke SD-WAN environment using the recommended (rendered) configuration, customized for my setup. However, I ran into a limitation: it seems I can't configure set add-route disable within the phase1-interface configuration.

The issue arises because the default setup is type = static, while the add-route option is only available when type = dynamic. This restriction is unexpected, especially since add-route = disable is a recommended setting in the docs for certain setups.

Is there a workaround, or is this something that could be addressed in a future update?

**Comment by dmitryperets** [comment]
Hi, 

The option `add-route` appears once you enable ADVPN (`set auto-discovery-receiver enable`). 
Otherwise there is no need to configure `set add-route disable`. 

It is possible that in the rendered config the line `set add-route disable` came before the line `set auto-discovery-receiver enable` (or that you didn't want to enable ADVPN in your case). Just make sure you put that line after the ADVPN line.
